# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='services',
            field=models.ManyToManyField(related_name='credentials', to='engine.Service'),
        ),
    ]
