# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
