# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20161230_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_creds', to='engine.Credential'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='engine.Team'),
        ),
    ]
