# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_credential_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='engine.Team'),
        ),
    ]
