# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20161230_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='plugin',
        ),
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
